# Generated by Django 2.0 on 2019-08-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhijiadaren', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time']},
        ),
    ]
