# Generated by Django 2.0 on 2019-09-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhijiadaren', '0006_auto_20190831_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
